name: scrape-and-post

on:
  schedule:
    # every 3 hours at hh:15 Paris time
    - cron: '15 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # — 1. check out repo ---------------------------------------------------
      - uses: actions/checkout@v4

      # — 2. Python 3.10 ------------------------------------------------------
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # — 3. install project dependencies (Playwright, Torch, Transformers …) -
      - run: pip install -r requirements.txt

      # — 4. Ubuntu libs Playwright browsers need -----------------------------
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2t64 \
            libgtk-3-0 \
            libdbus-glib-1-2

      # — 5. download headless Chromium **and** Firefox -----------------------
      - name: Install Playwright browsers
        run: python -m playwright install chromium firefox

      # — 6. run the existing Slack bot (ICEYE, Rocket Lab, …) ----------------
      - name: Run bot
