name: scrape-and-post

on:
  schedule:
    - cron: '15 */3 * * *'       # every 3 h at hh:15 Paris time
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt

      - name: Install libasound2t64
        run: sudo apt-get update && sudo apt-get install -y libasound2t64

      - name: Install Playwright browsers
        run: python -m playwright install chromium

      - name: Run bot
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_2 }}
        run: python news_bot.py
